# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: cheapass

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  region: us-west-1
  runtime: nodejs10.x
  timeout: 28
  versionFunctions: false

functions:
  cron:
    description: Trigger cron to crawl all alerts
    handler: handler.run  # This will require the handler.js file,
                          # and execute the exported run function
    environment:
      LAMBDA_ENDPOINT: ${file(./serverless.env.yml):dev.LAMBDA_ENDPOINT}

    events:
      - schedule: rate(15 minutes)

  crawl:
    description: Scrape webpage in background
    handler: handler.crawl

    events:
      - http:
          path: crawl
          method: post

  refresh-all:
    description: Forcefully refresh database
    handler: handler.run
    environment:
      LAMBDA_ENDPOINT: ${file(./serverless.env.yml):dev.LAMBDA_ENDPOINT}

    events:
      - http:
          path: run
          method: post
